/* Generated by mrlbmIRBC/lidDrivenCavity.m
 * Lid face: FRONT
 * Lid velocity: ux=0, uy=U_CHAR, uz=0
 * Single-phase moment order: rho, ux, uy, uz, mxx, myy, mzz, mxy, mxz, myz
 */

const real_t rho_I = [&]() -> real_t
{
    if constexpr (Q == 19)
    {
        return pop[0] + (((nodeType & (WEST)) == 0u) ? pop[1] : static_cast<real_t>(0)) + (((nodeType & (EAST)) == 0u) ? pop[2] : static_cast<real_t>(0)) + (((nodeType & (SOUTH)) == 0u) ? pop[3] : static_cast<real_t>(0)) + (((nodeType & (NORTH)) == 0u) ? pop[4] : static_cast<real_t>(0)) + (((nodeType & (BACK)) == 0u) ? pop[5] : static_cast<real_t>(0)) + (((nodeType & (FRONT)) == 0u) ? pop[6] : static_cast<real_t>(0)) + (((nodeType & (WEST | SOUTH)) == 0u) ? pop[7] : static_cast<real_t>(0)) + (((nodeType & (EAST | NORTH)) == 0u) ? pop[8] : static_cast<real_t>(0)) + (((nodeType & (WEST | BACK)) == 0u) ? pop[9] : static_cast<real_t>(0)) + (((nodeType & (EAST | FRONT)) == 0u) ? pop[10] : static_cast<real_t>(0)) + (((nodeType & (SOUTH | BACK)) == 0u) ? pop[11] : static_cast<real_t>(0)) + (((nodeType & (NORTH | FRONT)) == 0u) ? pop[12] : static_cast<real_t>(0)) + (((nodeType & (WEST | NORTH)) == 0u) ? pop[13] : static_cast<real_t>(0)) + (((nodeType & (EAST | SOUTH)) == 0u) ? pop[14] : static_cast<real_t>(0)) + (((nodeType & (WEST | FRONT)) == 0u) ? pop[15] : static_cast<real_t>(0)) + (((nodeType & (EAST | BACK)) == 0u) ? pop[16] : static_cast<real_t>(0)) + (((nodeType & (SOUTH | FRONT)) == 0u) ? pop[17] : static_cast<real_t>(0)) + (((nodeType & (NORTH | BACK)) == 0u) ? pop[18] : static_cast<real_t>(0));
    }
    else
    {
        return pop[0] + (((nodeType & (WEST)) == 0u) ? pop[1] : static_cast<real_t>(0)) + (((nodeType & (EAST)) == 0u) ? pop[2] : static_cast<real_t>(0)) + (((nodeType & (SOUTH)) == 0u) ? pop[3] : static_cast<real_t>(0)) + (((nodeType & (NORTH)) == 0u) ? pop[4] : static_cast<real_t>(0)) + (((nodeType & (BACK)) == 0u) ? pop[5] : static_cast<real_t>(0)) + (((nodeType & (FRONT)) == 0u) ? pop[6] : static_cast<real_t>(0)) + (((nodeType & (WEST | SOUTH)) == 0u) ? pop[7] : static_cast<real_t>(0)) + (((nodeType & (EAST | NORTH)) == 0u) ? pop[8] : static_cast<real_t>(0)) + (((nodeType & (WEST | BACK)) == 0u) ? pop[9] : static_cast<real_t>(0)) + (((nodeType & (EAST | FRONT)) == 0u) ? pop[10] : static_cast<real_t>(0)) + (((nodeType & (SOUTH | BACK)) == 0u) ? pop[11] : static_cast<real_t>(0)) + (((nodeType & (NORTH | FRONT)) == 0u) ? pop[12] : static_cast<real_t>(0)) + (((nodeType & (WEST | NORTH)) == 0u) ? pop[13] : static_cast<real_t>(0)) + (((nodeType & (EAST | SOUTH)) == 0u) ? pop[14] : static_cast<real_t>(0)) + (((nodeType & (WEST | FRONT)) == 0u) ? pop[15] : static_cast<real_t>(0)) + (((nodeType & (EAST | BACK)) == 0u) ? pop[16] : static_cast<real_t>(0)) + (((nodeType & (SOUTH | FRONT)) == 0u) ? pop[17] : static_cast<real_t>(0)) + (((nodeType & (NORTH | BACK)) == 0u) ? pop[18] : static_cast<real_t>(0)) + (((nodeType & (WEST | SOUTH | BACK)) == 0u) ? pop[19] : static_cast<real_t>(0)) + (((nodeType & (EAST | NORTH | FRONT)) == 0u) ? pop[20] : static_cast<real_t>(0)) + (((nodeType & (WEST | SOUTH | FRONT)) == 0u) ? pop[21] : static_cast<real_t>(0)) + (((nodeType & (EAST | NORTH | BACK)) == 0u) ? pop[22] : static_cast<real_t>(0)) + (((nodeType & (WEST | NORTH | BACK)) == 0u) ? pop[23] : static_cast<real_t>(0)) + (((nodeType & (EAST | SOUTH | FRONT)) == 0u) ? pop[24] : static_cast<real_t>(0)) + (((nodeType & (EAST | SOUTH | BACK)) == 0u) ? pop[25] : static_cast<real_t>(0)) + (((nodeType & (WEST | NORTH | FRONT)) == 0u) ? pop[26] : static_cast<real_t>(0));
    }
}();
const real_t inv_rho_I = static_cast<real_t>(1) / rho_I;

switch (nodeType)
{
case WEST_FACE:
{
    // IRBC static wall
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t mxy_I = (pop[8] - pop[14]) * inv_rho_I;
        const real_t mxz_I = (pop[10] - pop[16]) * inv_rho_I;

        rho = (static_cast<real_t>(6) * rho_I) / (static_cast<real_t>(5));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = (static_cast<real_t>(5) * mxy_I) / (static_cast<real_t>(3));
        mxz = (static_cast<real_t>(5) * mxz_I) / (static_cast<real_t>(3));
        myz = static_cast<real_t>(0);
    }
    else
    {
        // Incoming moments
        const real_t mxy_I = (pop[8] - pop[14] + pop[20] + pop[22] - pop[24] - pop[25]) * inv_rho_I;
        const real_t mxz_I = (pop[10] - pop[16] + pop[20] - pop[22] + pop[24] - pop[25]) * inv_rho_I;

        rho = (static_cast<real_t>(6) * rho_I) / (static_cast<real_t>(5));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = (static_cast<real_t>(5) * mxy_I) / (static_cast<real_t>(3));
        mxz = (static_cast<real_t>(5) * mxz_I) / (static_cast<real_t>(3));
        myz = static_cast<real_t>(0);
    }

    break;
}
case EAST_FACE:
{
    // IRBC static wall
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t mxy_I = (pop[7] - pop[13]) * inv_rho_I;
        const real_t mxz_I = (pop[9] - pop[15]) * inv_rho_I;

        rho = (static_cast<real_t>(6) * rho_I) / (static_cast<real_t>(5));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = (static_cast<real_t>(5) * mxy_I) / (static_cast<real_t>(3));
        mxz = (static_cast<real_t>(5) * mxz_I) / (static_cast<real_t>(3));
        myz = static_cast<real_t>(0);
    }
    else
    {
        // Incoming moments
        const real_t mxy_I = (pop[7] - pop[13] + pop[19] + pop[21] - pop[23] - pop[26]) * inv_rho_I;
        const real_t mxz_I = (pop[9] - pop[15] + pop[19] - pop[21] + pop[23] - pop[26]) * inv_rho_I;

        rho = (static_cast<real_t>(6) * rho_I) / (static_cast<real_t>(5));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = (static_cast<real_t>(5) * mxy_I) / (static_cast<real_t>(3));
        mxz = (static_cast<real_t>(5) * mxz_I) / (static_cast<real_t>(3));
        myz = static_cast<real_t>(0);
    }

    break;
}
case SOUTH_FACE:
{
    // IRBC static wall
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t mxy_I = (pop[8] - pop[13]) * inv_rho_I;
        const real_t myz_I = (pop[12] - pop[18]) * inv_rho_I;

        rho = (static_cast<real_t>(6) * rho_I) / (static_cast<real_t>(5));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = (static_cast<real_t>(5) * mxy_I) / (static_cast<real_t>(3));
        mxz = static_cast<real_t>(0);
        myz = (static_cast<real_t>(5) * myz_I) / (static_cast<real_t>(3));
    }
    else
    {
        // Incoming moments
        const real_t mxy_I = (pop[8] - pop[13] + pop[20] + pop[22] - pop[23] - pop[26]) * inv_rho_I;
        const real_t myz_I = (pop[12] - pop[18] + pop[20] - pop[22] - pop[23] + pop[26]) * inv_rho_I;

        rho = (static_cast<real_t>(6) * rho_I) / (static_cast<real_t>(5));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = (static_cast<real_t>(5) * mxy_I) / (static_cast<real_t>(3));
        mxz = static_cast<real_t>(0);
        myz = (static_cast<real_t>(5) * myz_I) / (static_cast<real_t>(3));
    }

    break;
}
case NORTH_FACE:
{
    // IRBC static wall
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t mxy_I = (pop[7] - pop[14]) * inv_rho_I;
        const real_t myz_I = (pop[11] - pop[17]) * inv_rho_I;

        rho = (static_cast<real_t>(6) * rho_I) / (static_cast<real_t>(5));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = (static_cast<real_t>(5) * mxy_I) / (static_cast<real_t>(3));
        mxz = static_cast<real_t>(0);
        myz = (static_cast<real_t>(5) * myz_I) / (static_cast<real_t>(3));
    }
    else
    {
        // Incoming moments
        const real_t mxy_I = (pop[7] - pop[14] + pop[19] + pop[21] - pop[24] - pop[25]) * inv_rho_I;
        const real_t myz_I = (pop[11] - pop[17] + pop[19] - pop[21] - pop[24] + pop[25]) * inv_rho_I;

        rho = (static_cast<real_t>(6) * rho_I) / (static_cast<real_t>(5));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = (static_cast<real_t>(5) * mxy_I) / (static_cast<real_t>(3));
        mxz = static_cast<real_t>(0);
        myz = (static_cast<real_t>(5) * myz_I) / (static_cast<real_t>(3));
    }

    break;
}
case BACK_FACE:
{
    // IRBC static wall
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t mxz_I = (pop[10] - pop[15]) * inv_rho_I;
        const real_t myz_I = (pop[12] - pop[17]) * inv_rho_I;

        rho = (static_cast<real_t>(6) * rho_I) / (static_cast<real_t>(5));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = (static_cast<real_t>(5) * mxz_I) / (static_cast<real_t>(3));
        myz = (static_cast<real_t>(5) * myz_I) / (static_cast<real_t>(3));
    }
    else
    {
        // Incoming moments
        const real_t mxz_I = (pop[10] - pop[15] + pop[20] - pop[21] + pop[24] - pop[26]) * inv_rho_I;
        const real_t myz_I = (pop[12] - pop[17] + pop[20] - pop[21] - pop[24] + pop[26]) * inv_rho_I;

        rho = (static_cast<real_t>(6) * rho_I) / (static_cast<real_t>(5));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = (static_cast<real_t>(5) * mxz_I) / (static_cast<real_t>(3));
        myz = (static_cast<real_t>(5) * myz_I) / (static_cast<real_t>(3));
    }

    break;
}
case FRONT_FACE:
{
    // IRBC moving lid (FRONT)
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t mxz_I = (pop[9] - pop[16]) * inv_rho_I;
        const real_t myz_I = (pop[11] - pop[18]) * inv_rho_I;

        rho = (static_cast<real_t>(6) * rho_I) / (static_cast<real_t>(5));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = (static_cast<real_t>(5) * mxz_I) / (static_cast<real_t>(3));
        myz = (static_cast<real_t>(5) * myz_I - U_CHAR) / (static_cast<real_t>(3));
    }
    else
    {
        // Incoming moments
        const real_t mxz_I = (pop[9] - pop[16] + pop[19] - pop[22] + pop[23] - pop[25]) * inv_rho_I;
        const real_t myz_I = (pop[11] - pop[18] + pop[19] - pop[22] - pop[23] + pop[25]) * inv_rho_I;

        rho = (static_cast<real_t>(6) * rho_I) / (static_cast<real_t>(5));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = (static_cast<real_t>(5) * mxz_I) / (static_cast<real_t>(3));
        myz = (static_cast<real_t>(5) * myz_I - U_CHAR) / (static_cast<real_t>(3));
    }

    break;
}
case SOUTH_WEST:
{
    // IRBC static wall
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t mxy_I = (pop[8]) * inv_rho_I;

        rho = (static_cast<real_t>(36) * mxy_I * OMEGA * rho_I - static_cast<real_t>(36) * mxy_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = (static_cast<real_t>(25) * mxy_I - static_cast<real_t>(1)) / (static_cast<real_t>(9) * mxy_I * OMEGA - static_cast<real_t>(9) * mxy_I + static_cast<real_t>(9));
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }
    else
    {
        // Incoming moments
        const real_t mxy_I = (pop[8] + pop[20] + pop[22]) * inv_rho_I;

        rho = (static_cast<real_t>(36) * mxy_I * OMEGA * rho_I - static_cast<real_t>(36) * mxy_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = (static_cast<real_t>(25) * mxy_I - static_cast<real_t>(1)) / (static_cast<real_t>(9) * mxy_I * OMEGA - static_cast<real_t>(9) * mxy_I + static_cast<real_t>(9));
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }

    break;
}
case SOUTH_EAST:
{
    // IRBC static wall
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t mxy_I = (-pop[13]) * inv_rho_I;

        rho = (-static_cast<real_t>(36) * mxy_I * OMEGA * rho_I + static_cast<real_t>(36) * mxy_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = (static_cast<real_t>(25) * mxy_I + static_cast<real_t>(1)) / (-static_cast<real_t>(9) * mxy_I * OMEGA + static_cast<real_t>(9) * mxy_I + static_cast<real_t>(9));
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }
    else
    {
        // Incoming moments
        const real_t mxy_I = (-pop[13] - pop[23] - pop[26]) * inv_rho_I;

        rho = (-static_cast<real_t>(36) * mxy_I * OMEGA * rho_I + static_cast<real_t>(36) * mxy_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = (static_cast<real_t>(25) * mxy_I + static_cast<real_t>(1)) / (-static_cast<real_t>(9) * mxy_I * OMEGA + static_cast<real_t>(9) * mxy_I + static_cast<real_t>(9));
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }

    break;
}
case NORTH_WEST:
{
    // IRBC static wall
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t mxy_I = (-pop[14]) * inv_rho_I;

        rho = (-static_cast<real_t>(36) * mxy_I * OMEGA * rho_I + static_cast<real_t>(36) * mxy_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = (static_cast<real_t>(25) * mxy_I + static_cast<real_t>(1)) / (-static_cast<real_t>(9) * mxy_I * OMEGA + static_cast<real_t>(9) * mxy_I + static_cast<real_t>(9));
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }
    else
    {
        // Incoming moments
        const real_t mxy_I = (-pop[14] - pop[24] - pop[25]) * inv_rho_I;

        rho = (-static_cast<real_t>(36) * mxy_I * OMEGA * rho_I + static_cast<real_t>(36) * mxy_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = (static_cast<real_t>(25) * mxy_I + static_cast<real_t>(1)) / (-static_cast<real_t>(9) * mxy_I * OMEGA + static_cast<real_t>(9) * mxy_I + static_cast<real_t>(9));
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }

    break;
}
case NORTH_EAST:
{
    // IRBC static wall
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t mxy_I = (pop[7]) * inv_rho_I;

        rho = (static_cast<real_t>(36) * mxy_I * OMEGA * rho_I - static_cast<real_t>(36) * mxy_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = (static_cast<real_t>(25) * mxy_I - static_cast<real_t>(1)) / (static_cast<real_t>(9) * mxy_I * OMEGA - static_cast<real_t>(9) * mxy_I + static_cast<real_t>(9));
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }
    else
    {
        // Incoming moments
        const real_t mxy_I = (pop[7] + pop[19] + pop[21]) * inv_rho_I;

        rho = (static_cast<real_t>(36) * mxy_I * OMEGA * rho_I - static_cast<real_t>(36) * mxy_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = (static_cast<real_t>(25) * mxy_I - static_cast<real_t>(1)) / (static_cast<real_t>(9) * mxy_I * OMEGA - static_cast<real_t>(9) * mxy_I + static_cast<real_t>(9));
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }

    break;
}
case WEST_BACK:
{
    // IRBC static wall
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t mxz_I = (pop[10]) * inv_rho_I;

        rho = (static_cast<real_t>(36) * mxz_I * OMEGA * rho_I - static_cast<real_t>(36) * mxz_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = (static_cast<real_t>(25) * mxz_I - static_cast<real_t>(1)) / (static_cast<real_t>(9) * mxz_I * OMEGA - static_cast<real_t>(9) * mxz_I + static_cast<real_t>(9));
        myz = static_cast<real_t>(0);
    }
    else
    {
        // Incoming moments
        const real_t mxz_I = (pop[10] + pop[20] + pop[24]) * inv_rho_I;

        rho = (static_cast<real_t>(36) * mxz_I * OMEGA * rho_I - static_cast<real_t>(36) * mxz_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = (static_cast<real_t>(25) * mxz_I - static_cast<real_t>(1)) / (static_cast<real_t>(9) * mxz_I * OMEGA - static_cast<real_t>(9) * mxz_I + static_cast<real_t>(9));
        myz = static_cast<real_t>(0);
    }

    break;
}
case WEST_FRONT:
{
    // IRBC moving lid (FRONT)
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t mxz_I = (-pop[16]) * inv_rho_I;

        rho = (-static_cast<real_t>(72) * mxz_I * OMEGA * rho_I + static_cast<real_t>(72) * mxz_I * rho_I + static_cast<real_t>(72) * rho_I) / (-static_cast<real_t>(3) * OMEGA * (U_CHAR * U_CHAR) + static_cast<real_t>(2) * OMEGA + static_cast<real_t>(48));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = (-static_cast<real_t>(3) * mxz_I * (U_CHAR * U_CHAR) + static_cast<real_t>(50) * mxz_I - static_cast<real_t>(3) * (U_CHAR * U_CHAR) + static_cast<real_t>(2)) / (-static_cast<real_t>(18) * mxz_I * OMEGA + static_cast<real_t>(18) * mxz_I + static_cast<real_t>(18));
        myz = static_cast<real_t>(0);
    }
    else
    {
        // Incoming moments
        const real_t mxz_I = (-pop[16] - pop[22] - pop[25]) * inv_rho_I;

        rho = (-static_cast<real_t>(36) * mxz_I * OMEGA * rho_I + static_cast<real_t>(36) * mxz_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = (static_cast<real_t>(25) * mxz_I + static_cast<real_t>(1)) / (-static_cast<real_t>(9) * mxz_I * OMEGA + static_cast<real_t>(9) * mxz_I + static_cast<real_t>(9));
        myz = static_cast<real_t>(0);
    }

    break;
}
case EAST_BACK:
{
    // IRBC static wall
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t mxz_I = (-pop[15]) * inv_rho_I;

        rho = (-static_cast<real_t>(36) * mxz_I * OMEGA * rho_I + static_cast<real_t>(36) * mxz_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = (static_cast<real_t>(25) * mxz_I + static_cast<real_t>(1)) / (-static_cast<real_t>(9) * mxz_I * OMEGA + static_cast<real_t>(9) * mxz_I + static_cast<real_t>(9));
        myz = static_cast<real_t>(0);
    }
    else
    {
        // Incoming moments
        const real_t mxz_I = (-pop[15] - pop[21] - pop[26]) * inv_rho_I;

        rho = (-static_cast<real_t>(36) * mxz_I * OMEGA * rho_I + static_cast<real_t>(36) * mxz_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = (static_cast<real_t>(25) * mxz_I + static_cast<real_t>(1)) / (-static_cast<real_t>(9) * mxz_I * OMEGA + static_cast<real_t>(9) * mxz_I + static_cast<real_t>(9));
        myz = static_cast<real_t>(0);
    }

    break;
}
case EAST_FRONT:
{
    // IRBC moving lid (FRONT)
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t mxz_I = (pop[9]) * inv_rho_I;

        rho = (static_cast<real_t>(72) * mxz_I * OMEGA * rho_I - static_cast<real_t>(72) * mxz_I * rho_I + static_cast<real_t>(72) * rho_I) / (-static_cast<real_t>(3) * OMEGA * (U_CHAR * U_CHAR) + static_cast<real_t>(2) * OMEGA + static_cast<real_t>(48));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = (-static_cast<real_t>(3) * mxz_I * (U_CHAR * U_CHAR) + static_cast<real_t>(50) * mxz_I + static_cast<real_t>(3) * (U_CHAR * U_CHAR) - static_cast<real_t>(2)) / (static_cast<real_t>(18) * mxz_I * OMEGA - static_cast<real_t>(18) * mxz_I + static_cast<real_t>(18));
        myz = static_cast<real_t>(0);
    }
    else
    {
        // Incoming moments
        const real_t mxz_I = (pop[9] + pop[19] + pop[23]) * inv_rho_I;

        rho = (static_cast<real_t>(36) * mxz_I * OMEGA * rho_I - static_cast<real_t>(36) * mxz_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = (static_cast<real_t>(25) * mxz_I - static_cast<real_t>(1)) / (static_cast<real_t>(9) * mxz_I * OMEGA - static_cast<real_t>(9) * mxz_I + static_cast<real_t>(9));
        myz = static_cast<real_t>(0);
    }

    break;
}
case SOUTH_BACK:
{
    // IRBC static wall
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t myz_I = (pop[12]) * inv_rho_I;

        rho = (static_cast<real_t>(36) * myz_I * OMEGA * rho_I - static_cast<real_t>(36) * myz_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = (static_cast<real_t>(25) * myz_I - static_cast<real_t>(1)) / (static_cast<real_t>(9) * myz_I * OMEGA - static_cast<real_t>(9) * myz_I + static_cast<real_t>(9));
    }
    else
    {
        // Incoming moments
        const real_t myz_I = (pop[12] + pop[20] + pop[26]) * inv_rho_I;

        rho = (static_cast<real_t>(36) * myz_I * OMEGA * rho_I - static_cast<real_t>(36) * myz_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = (static_cast<real_t>(25) * myz_I - static_cast<real_t>(1)) / (static_cast<real_t>(9) * myz_I * OMEGA - static_cast<real_t>(9) * myz_I + static_cast<real_t>(9));
    }

    break;
}
case SOUTH_FRONT:
{
    // IRBC moving lid (FRONT)
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t myz_I = (-pop[18]) * inv_rho_I;

        rho = (-static_cast<real_t>(36) * myz_I * OMEGA * rho_I + static_cast<real_t>(36) * myz_I * rho_I + static_cast<real_t>(36) * rho_I) / (static_cast<real_t>(3) * OMEGA * (U_CHAR * U_CHAR) - static_cast<real_t>(3) * OMEGA * U_CHAR + OMEGA - static_cast<real_t>(18) * (U_CHAR * U_CHAR) + static_cast<real_t>(18) * U_CHAR + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = (-static_cast<real_t>(15) * myz_I * (U_CHAR * U_CHAR) + static_cast<real_t>(15) * myz_I * U_CHAR + static_cast<real_t>(25) * myz_I + static_cast<real_t>(3) * (U_CHAR * U_CHAR) - static_cast<real_t>(3) * U_CHAR + static_cast<real_t>(1)) / (-static_cast<real_t>(9) * myz_I * OMEGA + static_cast<real_t>(9) * myz_I + static_cast<real_t>(9));
    }
    else
    {
        // Incoming moments
        const real_t myz_I = (-pop[18] - pop[22] - pop[23]) * inv_rho_I;

        rho = (-static_cast<real_t>(36) * myz_I * OMEGA * rho_I + static_cast<real_t>(36) * myz_I * rho_I + static_cast<real_t>(36) * rho_I) / (static_cast<real_t>(3) * OMEGA * (U_CHAR * U_CHAR) - static_cast<real_t>(3) * OMEGA * U_CHAR + OMEGA - static_cast<real_t>(18) * (U_CHAR * U_CHAR) + static_cast<real_t>(18) * U_CHAR + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = (-static_cast<real_t>(15) * myz_I * (U_CHAR * U_CHAR) + static_cast<real_t>(15) * myz_I * U_CHAR + static_cast<real_t>(25) * myz_I + static_cast<real_t>(3) * (U_CHAR * U_CHAR) - static_cast<real_t>(3) * U_CHAR + static_cast<real_t>(1)) / (-static_cast<real_t>(9) * myz_I * OMEGA + static_cast<real_t>(9) * myz_I + static_cast<real_t>(9));
    }

    break;
}
case NORTH_BACK:
{
    // IRBC static wall
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t myz_I = (-pop[17]) * inv_rho_I;

        rho = (-static_cast<real_t>(36) * myz_I * OMEGA * rho_I + static_cast<real_t>(36) * myz_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = (static_cast<real_t>(25) * myz_I + static_cast<real_t>(1)) / (-static_cast<real_t>(9) * myz_I * OMEGA + static_cast<real_t>(9) * myz_I + static_cast<real_t>(9));
    }
    else
    {
        // Incoming moments
        const real_t myz_I = (-pop[17] - pop[21] - pop[24]) * inv_rho_I;

        rho = (-static_cast<real_t>(36) * myz_I * OMEGA * rho_I + static_cast<real_t>(36) * myz_I * rho_I + static_cast<real_t>(36) * rho_I) / (OMEGA + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = (static_cast<real_t>(25) * myz_I + static_cast<real_t>(1)) / (-static_cast<real_t>(9) * myz_I * OMEGA + static_cast<real_t>(9) * myz_I + static_cast<real_t>(9));
    }

    break;
}
case NORTH_FRONT:
{
    // IRBC moving lid (FRONT)
    if constexpr (Q == 19)
    {
        // Incoming moments
        const real_t myz_I = (pop[11]) * inv_rho_I;

        rho = (static_cast<real_t>(36) * myz_I * OMEGA * rho_I - static_cast<real_t>(36) * myz_I * rho_I + static_cast<real_t>(36) * rho_I) / (static_cast<real_t>(3) * OMEGA * (U_CHAR * U_CHAR) + static_cast<real_t>(3) * OMEGA * U_CHAR + OMEGA - static_cast<real_t>(18) * (U_CHAR * U_CHAR) - static_cast<real_t>(18) * U_CHAR + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = (-static_cast<real_t>(15) * myz_I * (U_CHAR * U_CHAR) - static_cast<real_t>(15) * myz_I * U_CHAR + static_cast<real_t>(25) * myz_I - static_cast<real_t>(3) * (U_CHAR * U_CHAR) - static_cast<real_t>(3) * U_CHAR - static_cast<real_t>(1)) / (static_cast<real_t>(9) * myz_I * OMEGA - static_cast<real_t>(9) * myz_I + static_cast<real_t>(9));
    }
    else
    {
        // Incoming moments
        const real_t myz_I = (pop[11] + pop[19] + pop[25]) * inv_rho_I;

        rho = (static_cast<real_t>(36) * myz_I * OMEGA * rho_I - static_cast<real_t>(36) * myz_I * rho_I + static_cast<real_t>(36) * rho_I) / (static_cast<real_t>(3) * OMEGA * (U_CHAR * U_CHAR) + static_cast<real_t>(3) * OMEGA * U_CHAR + OMEGA - static_cast<real_t>(18) * (U_CHAR * U_CHAR) - static_cast<real_t>(18) * U_CHAR + static_cast<real_t>(24));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = (-static_cast<real_t>(15) * myz_I * (U_CHAR * U_CHAR) - static_cast<real_t>(15) * myz_I * U_CHAR + static_cast<real_t>(25) * myz_I - static_cast<real_t>(3) * (U_CHAR * U_CHAR) - static_cast<real_t>(3) * U_CHAR - static_cast<real_t>(1)) / (static_cast<real_t>(9) * myz_I * OMEGA - static_cast<real_t>(9) * myz_I + static_cast<real_t>(9));
    }

    break;
}
case NORTH_WEST_FRONT:
{
    // IRBC moving lid (FRONT)
    if constexpr (Q == 19)
    {

        rho = (-static_cast<real_t>(24) * rho_I) / (static_cast<real_t>(9) * (U_CHAR * U_CHAR) + static_cast<real_t>(8) * U_CHAR - static_cast<real_t>(14));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }
    else
    {

        rho = (-static_cast<real_t>(216) * rho_I) / (static_cast<real_t>(75) * (U_CHAR * U_CHAR) + static_cast<real_t>(75) * U_CHAR - static_cast<real_t>(125));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }

    break;
}
case NORTH_WEST_BACK:
{
    // IRBC static wall
    if constexpr (Q == 19)
    {

        rho = (static_cast<real_t>(12) * rho_I) / (static_cast<real_t>(7));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }
    else
    {

        rho = (static_cast<real_t>(216) * rho_I) / (static_cast<real_t>(125));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }

    break;
}
case NORTH_EAST_FRONT:
{
    // IRBC moving lid (FRONT)
    if constexpr (Q == 19)
    {

        rho = (-static_cast<real_t>(24) * rho_I) / (static_cast<real_t>(9) * (U_CHAR * U_CHAR) + static_cast<real_t>(8) * U_CHAR - static_cast<real_t>(14));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }
    else
    {

        rho = (-static_cast<real_t>(216) * rho_I) / (static_cast<real_t>(75) * (U_CHAR * U_CHAR) + static_cast<real_t>(75) * U_CHAR - static_cast<real_t>(125));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }

    break;
}
case NORTH_EAST_BACK:
{
    // IRBC static wall
    if constexpr (Q == 19)
    {

        rho = (static_cast<real_t>(12) * rho_I) / (static_cast<real_t>(7));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }
    else
    {

        rho = (static_cast<real_t>(216) * rho_I) / (static_cast<real_t>(125));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }

    break;
}
case SOUTH_WEST_FRONT:
{
    // IRBC moving lid (FRONT)
    if constexpr (Q == 19)
    {

        rho = (static_cast<real_t>(24) * rho_I) / (-static_cast<real_t>(9) * (U_CHAR * U_CHAR) + static_cast<real_t>(8) * U_CHAR + static_cast<real_t>(14));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }
    else
    {

        rho = (static_cast<real_t>(216) * rho_I) / (-static_cast<real_t>(75) * (U_CHAR * U_CHAR) + static_cast<real_t>(75) * U_CHAR + static_cast<real_t>(125));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }

    break;
}
case SOUTH_WEST_BACK:
{
    // IRBC static wall
    if constexpr (Q == 19)
    {

        rho = (static_cast<real_t>(12) * rho_I) / (static_cast<real_t>(7));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }
    else
    {

        rho = (static_cast<real_t>(216) * rho_I) / (static_cast<real_t>(125));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }

    break;
}
case SOUTH_EAST_FRONT:
{
    // IRBC moving lid (FRONT)
    if constexpr (Q == 19)
    {

        rho = (static_cast<real_t>(24) * rho_I) / (-static_cast<real_t>(9) * (U_CHAR * U_CHAR) + static_cast<real_t>(8) * U_CHAR + static_cast<real_t>(14));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }
    else
    {

        rho = (static_cast<real_t>(216) * rho_I) / (-static_cast<real_t>(75) * (U_CHAR * U_CHAR) + static_cast<real_t>(75) * U_CHAR + static_cast<real_t>(125));
        ux = static_cast<real_t>(0);
        uy = U_CHAR;
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = (U_CHAR * U_CHAR);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }

    break;
}
case SOUTH_EAST_BACK:
{
    // IRBC static wall
    if constexpr (Q == 19)
    {

        rho = (static_cast<real_t>(12) * rho_I) / (static_cast<real_t>(7));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }
    else
    {

        rho = (static_cast<real_t>(216) * rho_I) / (static_cast<real_t>(125));
        ux = static_cast<real_t>(0);
        uy = static_cast<real_t>(0);
        uz = static_cast<real_t>(0);
        mxx = static_cast<real_t>(0);
        myy = static_cast<real_t>(0);
        mzz = static_cast<real_t>(0);
        mxy = static_cast<real_t>(0);
        mxz = static_cast<real_t>(0);
        myz = static_cast<real_t>(0);
    }

    break;
}
default:
{
    break;
}
}
